### ISSUE TITLE
Does It work With Navigation Controller?

### ISSUE THREAD

**Issue by Tarektouati** [Ramotion/elongation-preview#6]
Hey like your work !
Just does it with Navigation Controller? 
because can't get it working !

Thanks

**Comment by hoffsilva** [comment]
Hey @Tarektouati! 
How are you? 
What is your error?

**Comment by michaeldai1006** [comment]
I cant get it working with Tabbar, I believe it is a similar error with Tarektouati. My error message:
Can't get `ElongationViewController` from UINavigationController nor from context's viewController itself.

**Comment by michaeldai1006** [comment]
Oh I actually just get this problem solved! Since the ElongationViewController is embedded into NavigationViewController or TabBarViewController, ElonggationTransition class's root method cant get access to the ElongationViewController. In my situation, I implemented UITabBar, I manually returned the ElongationViewController:
`let tabbarController =  UIApplication.shared.keyWindow?.rootViewController as! UITabBarController
    return tabbarController.viewControllers![1] as! ElongationViewController`

**Comment by hoffsilva** [comment]
@Tarektouati i did the same thing in my app. ;)

**Comment by hoffsilva** [comment]
@TDClash  i did the same thing in my app. ;)

**Comment by kuraydev** [comment]
@TDClash Can you tell where should i manually edit your code?? I want to use elongation preview with tabbar but could not solve it

**Comment by av0c0der** [comment]
I'll look on this issue soon, was busy on a project. Sorry.

Actually, there are closed issue #3 just like this one. Maybe it'll help someone, but here we need some refactoring.

**Comment by kuraydev** [comment]
@Jauzee Any on going process about this issue? I really need a solution from you :)

**Comment by av0c0der** [comment]
@WrathChaos actually we have pushed 1.1.0 version with fix for `UITabBarController`, but currently I can't push Pod update because I can't receive authentication email from @Cocoapods 

Please checkout the repo manually and check how it works now.

If your issue wasn't fixed, please give me more details about your screens flow.

**Comment by Stefania66** [comment]
Come avete risolto? Mi aiutate per favore. Ho inserito la libreria nel mio progetto ma mi dice Can't get `ElongationViewController` from UINavigationController nor from context's viewController itself. Grazie da Stefania
